openapi: 3.0.0
info:
  title: Bug Archive API
  version: 1.0.0
paths:
  /api/admin/dashboard/bug-archive:
    get:
      summary: Retrieve the bug archive
      responses:
        '200':
          description: A list of bugs in the archive
          content:
            application/json:
              schema:
                type: object
                properties:
                  archive:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        description:
                          type: string
                        submittedBy:
                          type: string
                        dateSubmitted:
                          type: string
                          format: date
        '400':
          description: Bad request
        '500':
          description: Internal server error