name: Snyk Security Scan

on:
  pull_request:
    branches:
      - f24
  workflow_call:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  checks: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: .install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run Snyk Test
        run: npx snyk test --severity-threshold=high
        working-directory: .install
